export type MockedTextOptions =
  | "chat gpt"
  | "inteligência artificial"
  | "elon musk"
  | "cyber truck"
  | "5g brasil"
  | "criptomoeda"
  | "startup brasileira"
  | "privacidade dado"
  | "meditação"
  | "saúde mental"
  | "ansiedade"
  | "depressão"
  | "terapia alternativa"
  | "terapia online"
  | "burnout"
  | "dengue"
  | "eleições municipais"
  | "anitta"
  | "privatiza praia"
  | "reforma tributária"
  | "marco temporal"
  | "congresso nacional"
  | "endrick"
  | "política inclusão"
  | "meio ambiente"
  | "gta 6"
  | "copa feminina"
  | "flamengo"
  | "palmeiras"
  | "neymar"
  | "melhor série"
  | "olimpíadas paris"
  | "oscar"
  | "spacex"
  | "missão artemis"
  | "james web"
  | "explora marte"
  | "buraco negro"
  | "amazônia"
  | "mudança climática"
  | "astrobiologia"
  | "empreendedorismo"
  | "vaga tecnologia"
  | "maior salario"
  | "mercado imobiliário"
  | "inflação brasil"
  | "taxa selic"
  | "ensino híbrido"
  | "intercâmbio";
