export const ONBOARDING_STEPS = {
  1: "welcome",
  2: "userIdentification",
  3: "freeSearch",
  4: "searchResult",
} as const;

export const ONBOARDING_OPTIONS = [
  "Sou um criador de conteúdo digital",
  "Trabalho com marketing",
  "Sou editor de vídeo",
  "Sou estudante",
  "Sou um entusiasta de podcasts",
  "Sou apenas um curioso",
];

export const ONBOARDING_SEARCH_OPTIONS = {
  "Tecnologia e Inovação": [
    "chat gpt",
    "inteligência artificial",
    "elon musk",
    "cyber truck",
    "5g brasil",
    "criptomoeda",
    "startup brasileira",
    "privacidade dado",
  ],
  "Saúde e Bem-Estar": [
    "meditação",
    "saúde mental",
    "ansiedade",
    "depressão",
    "terapia alternativa",
    "terapia online",
    "burnout",
    "dengue",
  ],
  "Cultura, Política e Sociedade": [
    "eleições municipais",
    "anitta",
    "privatiza praia",
    "reforma tributária",
    "marco temporal",
    "congresso nacional",
    "endrick",
    "política inclusão",
    "meio ambiente",
  ],
  "Esportes e Entretenimento": [
    "gta 6",
    "copa feminina",
    "flamengo",
    "palmeiras",
    "neymar",
    "melhor série",
    "olimpíadas paris",
    "oscar",
  ],
  "Ciência e Espaço": [
    "spacex",
    "missão artemis",
    "james web",
    "explora marte",
    "buraco negro",
    "amazônia",
    "mudança climática",
    "astrobiologia",
  ],
  "Economia e Negócios": [
    "empreendedorismo",
    "vaga tecnologia",
    "maior salario",
    "mercado imobiliário",
    "inflação brasil",
    "taxa selic",
    "ensino híbrido",
    "intercâmbio",
  ],
};
